# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d2b786e8f67fcf9aef9e135638dbbb6938dc7d10960c176716601cd6e9929b8e99f28909f3839f44312de9f18e82ab0b014e761613ee6102be672cbb8de3b2e

test:
  secret_key_base: 6c3ac7b3a57d0e320494526e195140668c1fc0d18613bc6b9a7ff5448616bc97c67ed5b4829bdf1933ddd4e71f97f45b2f0aa265a6acde19fc8dc530e3795fff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  linkedin_key: <%= ENV["LINKEDIN_KEY"] %>
  linkedin_secret: <%= ENV["LINKEDIN_SECRET"] %>
